// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;


public enum MessageState
{
		CORRECT=1,
		INCORRECT=2,
		INTRO,INTROTWO,INTROTHIR,
		INTOTHIRTEEN,
		NORMAL,
		SHELF,
		DOZO,
		HIKIDASHI,
		ELE,
		NOCROSS,
		NOCROSSTEST,
		ONENOKEY,
		ONEWITHKEY,
		ONEWITHKEYSCROL,
		UNDERNOKEY,
		UNDERWITHKEY,
		UNDERWITHKEYSCROL,
		UNDERWITHONEKEY,
}


