// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace AssemblyCSharp
{
// 音量クラス
		[Serializable]
		public class SoundVolume{
				public float BGM = 1.0f;
				public float Voice = 1.0f;
				public float SE = 1.0f;
				public bool Mute = false;

				public void Init(){
						BGM = 1.0f;
						Voice = 1.0f;
						SE = 1.0f;
						Mute = false;
				}
		}
}

